// netlify/functions/weekly-rebuild.js
// On-demand HTTP rebuild of TOMORROW's Weekly Best-of email, bypassing the
// Thursday-evening cron gate. Token-protected. Use this to regenerate the
// stored email after a fix (e.g. the AI copy) so Friday's 06:30 broadcast sends
// the new version instead of whatever the scheduled build froze earlier.
//
//   /.netlify/functions/weekly-rebuild?token=YOUR_WEEKLY_CANCEL_TOKEN
//
// It runs the SAME build as weekly-preview.js (same functions, imported), stores
// the blob quiz-meta/weekly-built-{friday} that weekly-broadcast reads, and
// re-emails you the preview so you can see the regenerated copy.

const wp = require('./weekly-preview');

exports.handler = async function(event) {
  const params = (event && event.queryStringParameters) || {};
  const REBUILD_TOKEN = process.env.WEEKLY_REBUILD_TOKEN || process.env.WEEKLY_CANCEL_TOKEN;
  if (!REBUILD_TOKEN || params.token !== REBUILD_TOKEN) {
    return htmlResp(403, 'Not authorised', 'Append <code>?token=YOUR_WEEKLY_CANCEL_TOKEN</code> to the URL.');
  }

  const env = {
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    SHEET_ID:       process.env.GOOGLE_SHEET_ID,
    API_KEY:        process.env.GOOGLE_API_KEY,
    SITE_ID:        process.env.NETLIFY_SITE_ID,
    TOKEN:          process.env.NETLIFY_API_TOKEN,
    REPORT_EMAIL:   process.env.DAILY_REPORT_EMAIL,
    CANCEL_TOKEN:   process.env.WEEKLY_CANCEL_TOKEN,
  };
  for (const k of Object.keys(env)) {
    if (!env[k]) return htmlResp(500, 'Missing env var', `Not set: <code>${k}</code>`);
  }

  // Same target as the scheduled build: tomorrow (UK time) = the Friday send day.
  const fridayISO = wp.addDaysISO(wp.londonDateISO(), 1);

  try {
    const questions = await wp.fetchWeeklyQuestions({ SHEET_ID: env.SHEET_ID, API_KEY: env.API_KEY, fridayISO, SITE_ID: env.SITE_ID, TOKEN: env.TOKEN });
    if (!questions.length) {
      return htmlResp(200, 'Nothing to rebuild', `No questions are flagged "W" for the week ending ${fridayISO}.`);
    }

    const avgPct = wp.weeklyAvgPct(questions);
    const statText = avgPct !== null ? `Players are averaging <strong>${avgPct}%</strong> on these. How would you do?` : null;

    const subjectQ = wp.pickSubjectQuestion(questions, fridayISO);
    const hero = (subjectQ && subjectQ.image) || (questions.find(q => q.image) || {}).image || null;

    let aiIntroNote;
    const copy = await wp.generateCopy(questions)
      .then(c => { aiIntroNote = `intro copy generated by ${c._model}`; return c; })
      .catch(err => {
        console.error('rebuild: AI copy failed, using fallback:', err.message);
        aiIntroNote = `intro copy FELL BACK to template: ${err.message}`;
        return wp.fallbackCopy(questions);
      });

    const whenlyPromo = await wp.buildWhenlyPromo(fridayISO).catch(err => {
      console.error('rebuild: Whenly promo failed, omitting block:', err.message);
      return null;
    });
    const aiWhenlyNote = whenlyPromo ? whenlyPromo.note : 'no Whenly promo this week';

    const whatwordPromo = await wp.buildWhatWordPromo(fridayISO).catch(err => {
      console.error('rebuild: What Word promo failed, omitting block:', err.message);
      return null;
    });
    const aiWhatWordNote = whatwordPromo ? whatwordPromo.note : 'no What Word promo this week';

    const groupiePromo = await wp.buildGroupiePromo(fridayISO).catch(err => {
      console.error('rebuild: Groupie promo failed, omitting block:', err.message);
      return null;
    });
    const aiGroupieNote = groupiePromo ? groupiePromo.note : 'no Groupie promo this week';

    const cleanHtml = wp.buildTeaserHtml({
      kicker: copy.kicker, headline: copy.headline, intro: copy.intro,
      hero, statText, fridayISO, whenlyPromo, whatwordPromo, groupiePromo,
    });
    const subject = subjectQ ? subjectQ.question : "This week's Pub Quiz Daily Best-of 🍺";

    // Overwrite the stored build so Friday's broadcast sends this one.
    await wp.putBlob(env.SITE_ID, env.TOKEN, `weekly-built-${fridayISO}`, { subject, html: cleanHtml, builtAt: new Date().toISOString(), rebuilt: true });
    await wp.deleteBlob(env.SITE_ID, env.TOKEN, `weekly-cancel-${fridayISO}`);

    const cancelUrl = `${wp.BASE}/.netlify/functions/weekly-cancel?token=${encodeURIComponent(env.CANCEL_TOKEN)}&week=${fridayISO}`;
    const previewHtml = wp.buildPreviewWrapper(cleanHtml.replace('%%UNSUB%%', '#'), { subject, fridayISO, cancelUrl, aiIntroNote, aiWhenlyNote, aiWhatWordNote, aiGroupieNote });

    await wp.sendEmail(env.RESEND_API_KEY, env.REPORT_EMAIL,
      `[Rebuilt] ${subject}  (sends 06:30 tomorrow)`,
      `Rebuilt preview of tomorrow's Weekly Best-of (sends 06:30 UK).\nSubject: ${subject}\nTo cancel this week's send, open: ${cancelUrl}`,
      previewHtml);

    console.log(`weekly-rebuild: rebuilt + previewed for ${fridayISO} (${questions.length} questions)`);
    return htmlResp(200, 'Rebuilt ✓',
      `Tomorrow's email (${questions.length} questions) has been regenerated and the preview re-sent to your inbox. Friday's 06:30 send will now use this version.` +
      `<br><br><b>AI intro:</b> ${wp.escapeHtml(aiIntroNote || '')}<br><b>Whenly:</b> ${wp.escapeHtml(aiWhenlyNote || '')}<br><b>What Word:</b> ${wp.escapeHtml(aiWhatWordNote || '')}<br><b>Groupie:</b> ${wp.escapeHtml(aiGroupieNote || '')}`);
  } catch (e) {
    console.error('weekly-rebuild error:', e);
    return htmlResp(500, 'Rebuild failed', wp.escapeHtml(String((e && e.message) || e)));
  }
};

function htmlResp(code, title, body) {
  return {
    statusCode: code,
    headers: { 'content-type': 'text/html; charset=utf-8' },
    body: `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${title}</title></head>` +
      `<body style="margin:0;background:#faf9f7;"><div style="font-family:system-ui,Arial,sans-serif;max-width:560px;margin:56px auto;padding:0 22px;color:#1a1a1a;">` +
      `<div style="font-family:Georgia,serif;font-size:22px;font-weight:700;margin-bottom:10px;">${title}</div>` +
      `<div style="font-size:15px;line-height:1.65;color:#555;">${body}</div>` +
      `<div style="font-size:12px;color:#b3aea6;margin-top:28px;">Pub Quiz Daily · weekly-rebuild</div></div></body></html>`,
  };
}
